<a href="https://colab.research.google.com/github/Dawood-Ali123/Pytorch_learning/blob/main/DataLoaderAndDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dataset** class fetch the data form the memory It use three method
. __init()__ it is used how to load or from where to get data
.__len()__it is very simple it is used to find the lenght of the sample or the batch size of the data
.__getitem()__it is used to return the particular row using the index
**DataLoader** it fetches the row form the dataset class and sufflle its indixes and make the batches of the indixes and call the dataset method.__get__item() and using this method ot convert the indixezs into the rows

In [8]:
#Step 1 import the necessary libraries
from sklearn.datasets import make_classification
import torch

In [2]:
#Step Create a synthetic classification dataset using sklearn
X,y=make_classification(
    n_samples=1000,#no of the samples
    n_features=10, #no of the features
    n_classes=2, #no of the class
    n_redundant=0, #no of the redundant features
    n_informative=2,#no of the informative feature
    random_state=42# for reproductivitiy
    )

In [3]:
X

array([[-2.05032063e+00,  1.21194399e+00, -1.26947067e+00, ...,
        -3.69277139e-01, -1.35267029e+00,  4.08652811e-01],
       [-7.59203084e-01, -3.23167666e-01, -1.22319413e+00, ...,
        -5.18637997e-01, -1.95434847e-01, -8.63378582e-02],
       [-2.72451497e-01, -6.11001124e-01, -5.70033885e-01, ...,
        -1.62171696e-03, -1.70478591e+00, -3.91156372e-01],
       ...,
       [-1.01462433e+00, -6.30845551e-01,  1.65314873e+00, ...,
         7.69031655e-01, -1.77768096e+00,  3.98763764e-01],
       [ 1.03661510e+00, -1.58718807e+00,  1.18675861e+00, ...,
         6.23525799e-01,  1.35580534e+00, -4.26571253e-01],
       [-1.88371388e+00,  1.44887833e-01, -1.30151180e+00, ...,
        -3.51414236e-01, -1.39930617e+00,  1.53236772e+00]])

In [5]:
y

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,

In [7]:
print(X.shape)
print(y.shape)

(1000, 10)
(1000,)


In [15]:
#firsr we have to convert the arrays into tensor
x=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

/tmp/ipykernel_2028/3336656416.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y=torch.tensor(y,dtype=torch.long)


In [16]:
from torch.utils.data import Dataset,DataLoader

In [33]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    #it set the
    self.features=features
    self.labels=labels;
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,index):
    return self.features[index],self.labels[index]


In [34]:
dataset=CustomDataset(x,y)

In [35]:
print(len(dataset))
print(dataset[0])

1000
(tensor([-2.0503,  1.2119, -1.2695,  0.1434, -1.0294, -1.7762,  0.2613, -0.3693,
        -1.3527,  0.4087]), tensor(0))


What is the magic function
Magic Function is also called the dunder method in the python which is automatically called by the class

In [36]:
#Now we are going to start the data loader
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)

In [37]:
for batch_features , batch_labels in dataloader:
  print(batch_features.shape)
  print(batch_labels.shape)

torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([32, 10])
torch.Size([32])
torch.Size([