<a href="https://colab.research.google.com/github/Dawood-Ali123/Pytorch_learning/blob/main/pytorchTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.10.0+cu128


In [4]:
if torch.cuda.is_available():
  print("GPU IS AVIALABLE ")
  print(f"USING GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU IS AVIALABLE 
USING GPU : Tesla T4


In [5]:
#using empty
a=torch.empty(2,3)

In [6]:
type(a)

torch.Tensor

In [7]:
print(a)

tensor([[-2.2638e+38,  4.5894e-41, -2.2638e+38],
        [ 4.5894e-41,  0.0000e+00,  0.0000e+00]])


In [8]:
#using zeros
b=torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using the rand
torch.rand(2,3)

tensor([[0.2639, 0.2949, 0.7339],
        [0.9556, 0.4369, 0.8856]])

In [11]:
#using the seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#if college using the same seed same tensor accour
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#arrange
print("Using the arrange -> ",torch.arange(0,10,2))
#using the linespace
print("Using linespace ->",torch.linspace(0,10,10))

Using the arrange ->  tensor([0, 2, 4, 6, 8])
Using linespace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [15]:
#using the Eye
print("using eye->",torch.eye(5))
#using full
print("using full->",torch.full((3,3),5))

using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [16]:
x=torch.tensor([[1,2,4],[4,5,6]])
x.shape

torch.Size([2, 3])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.empty_like(x)

tensor([[699444480, 699691472,         0],
        [        0,         0,         0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
#torch.rand_like(x)
#this cannont work beacase the x vales are the integer and the rand generate the valeue
#between the 0_1 and they are the float number sp it is not working heer we have to explicity type here


In [21]:
#find the dtype
x.dtype

torch.int64

In [22]:
torch.tensor([1,2,3],dtype=float)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
x.to(torch.float32)

tensor([[1., 2., 4.],
        [4., 5., 6.]])

In [24]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(2,3),low=10,high=20)
print(a)
print(b)

tensor([[2, 8, 8],
        [0, 4, 3]])
tensor([[18, 18, 14],
        [14, 11, 10]])


In [25]:
#mathematiacal operation
print(a+2)
print(a-2)
print(a*2)
print(a/3)
print((a*100)//3)
print(((a*100)//3)%2)
print(x**2)

tensor([[ 4, 10, 10],
        [ 2,  6,  5]])
tensor([[ 0,  6,  6],
        [-2,  2,  1]])
tensor([[ 4, 16, 16],
        [ 0,  8,  6]])
tensor([[0.6667, 2.6667, 2.6667],
        [0.0000, 1.3333, 1.0000]])
tensor([[ 66, 266, 266],
        [  0, 133, 100]])
tensor([[0, 0, 0],
        [0, 1, 0]])
tensor([[ 1,  4, 16],
        [16, 25, 36]])


In [26]:
#Element wise operation
print(a+b)
print(a-b)
print(a/2)
print(a%b)
print(a//b)
print(a**b)

tensor([[20, 26, 22],
        [14, 15, 13]])
tensor([[-16, -10,  -6],
        [-14,  -7,  -7]])
tensor([[1.0000, 4.0000, 4.0000],
        [0.0000, 2.0000, 1.5000]])
tensor([[2, 8, 8],
        [0, 4, 3]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[           262144, 18014398509481984,     4398046511104],
        [                0,           4194304,             59049]])


In [29]:
#more operation
d=torch.linspace(-2,4,10)
d

tensor([-2.0000e+00, -1.3333e+00, -6.6667e-01,  5.9605e-08,  6.6667e-01,
         1.3333e+00,  2.0000e+00,  2.6667e+00,  3.3333e+00,  4.0000e+00])

In [32]:
print(torch.abs(d))
print(torch.round(d))
print(torch.negative(d))
print(torch.ceil(d))
print(torch.floor(d))
print(torch.clamp(d,min=2,max=3))

tensor([2.0000e+00, 1.3333e+00, 6.6667e-01, 5.9605e-08, 6.6667e-01, 1.3333e+00,
        2.0000e+00, 2.6667e+00, 3.3333e+00, 4.0000e+00])
tensor([-2., -1., -1.,  0.,  1.,  1.,  2.,  3.,  3.,  4.])
tensor([ 2.0000e+00,  1.3333e+00,  6.6667e-01, -5.9605e-08, -6.6667e-01,
        -1.3333e+00, -2.0000e+00, -2.6667e+00, -3.3333e+00, -4.0000e+00])
tensor([-2., -1., -0.,  1.,  1.,  2.,  2.,  3.,  4.,  4.])
tensor([-2., -2., -1.,  0.,  0.,  1.,  2.,  2.,  3.,  4.])
tensor([2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.0000, 2.6667, 3.0000,
        3.0000])


In [33]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
f

tensor([[9., 9., 8.],
        [0., 7., 0.]], dtype=torch.float64)

In [36]:
print(torch.sum(f))
print(torch.sum(f,dim=0))
print(torch.sum(f,dim=1))
print(torch.mean(f))
print(torch.mean(f,dim=0))
print(torch.mean(f,dim=1))
print(torch.max(f))
print(torch.min(f))
print(torch.median(f))
print(torch.prod(f))
print(torch.argmax(f))
print(torch.argmin(f))
print(torch.var(f))
print(torch.std(f))

tensor(33., dtype=torch.float64)
tensor([ 9., 16.,  8.], dtype=torch.float64)
tensor([26.,  7.], dtype=torch.float64)
tensor(5.5000, dtype=torch.float64)
tensor([4.5000, 8.0000, 4.0000], dtype=torch.float64)
tensor([8.6667, 2.3333], dtype=torch.float64)
tensor(9., dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(7., dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(0)
tensor(3)
tensor(18.7000, dtype=torch.float64)
tensor(4.3243, dtype=torch.float64)


In [39]:
#matrix3 operation
print(torch.multiply(a,b))
x=torch.tensor([1,2])
y=torch.tensor([3,4])
print(torch.dot(x,y))

tensor([[ 36, 144, 112],
        [  0,  44,  30]])
tensor(11)


In [44]:
#transpose
print(torch.transpose(f,0,1))

tensor([[9., 0.],
        [9., 7.],
        [8., 0.]], dtype=torch.float64)


In [45]:
h=torch.rand(2,2)
print(torch.det(h))
print(torch.inverse(h))

tensor(0.1675)
tensor([[ 1.3184, -2.5276],
        [-0.1009,  4.7204]])


In [46]:
#comparision operator
print(a>b)
print(a<b)
print(a==b)
print(a!=b)


tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


In [50]:
#sum special function
print(torch.softmax(f,dim=0))
print(torch.log(f))
print(torch.exp(f))
print(torch.sigmoid(f))
print(torch.relu(f))

tensor([[9.9988e-01, 8.8080e-01, 9.9966e-01],
        [1.2339e-04, 1.1920e-01, 3.3535e-04]], dtype=torch.float64)
tensor([[2.1972, 2.1972, 2.0794],
        [  -inf, 1.9459,   -inf]], dtype=torch.float64)
tensor([[8.1031e+03, 8.1031e+03, 2.9810e+03],
        [1.0000e+00, 1.0966e+03, 1.0000e+00]], dtype=torch.float64)
tensor([[0.9999, 0.9999, 0.9997],
        [0.5000, 0.9991, 0.5000]], dtype=torch.float64)
tensor([[9., 9., 8.],
        [0., 7., 0.]], dtype=torch.float64)


In [53]:
#inpalce operation
print(a.add_(b))
print(a.relu_())

tensor([[56, 62, 50],
        [42, 37, 33]])
tensor([[56, 62, 50],
        [42, 37, 33]])


In [54]:
#Copy function
t=a.clone()
print(t)

tensor([[56, 62, 50],
        [42, 37, 33]])


In [61]:
#tensor operation on the cuda
device=torch.device('cuda')
#creating a new tensor on the gpu
print(torch.rand((2,3),device=device))
#Moving the existing tensor to the GPU
s=f.to(device)
print(s+5)

tensor([[0.7582, 0.0950, 0.8895],
        [0.9603, 0.9365, 0.4806]], device='cuda:0')
tensor([[14., 14., 13.],
        [ 5., 12.,  5.]], device='cuda:0', dtype=torch.float64)


In [64]:
#reshape
h=torch.ones(4,4)
print(h.reshape(2,2,2,2))
print(h.flatten())

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [66]:
#permute
g=torch.rand(2,3,4)
print(g)
#apply the permute
print(g.permute(2,0,1))

tensor([[[0.3039, 0.6726, 0.5740, 0.9233],
         [0.9178, 0.7590, 0.7775, 0.6179],
         [0.3379, 0.2170, 0.9454, 0.7116]],

        [[0.1157, 0.6574, 0.3451, 0.0453],
         [0.9798, 0.5548, 0.6868, 0.4920],
         [0.0748, 0.9605, 0.3271, 0.0103]]])
tensor([[[0.3039, 0.9178, 0.3379],
         [0.1157, 0.9798, 0.0748]],

        [[0.6726, 0.7590, 0.2170],
         [0.6574, 0.5548, 0.9605]],

        [[0.5740, 0.7775, 0.9454],
         [0.3451, 0.6868, 0.3271]],

        [[0.9233, 0.6179, 0.7116],
         [0.0453, 0.4920, 0.0103]]])


In [70]:
#unsqueeze and squeeze
k=torch.rand(226,226,3)
print(k.unsqueeze_(0).shape)
#squueze
d=torch.rand(0,20)
print(d.squeeze_(0).shape)

torch.Size([1, 226, 226, 3])
torch.Size([0, 20])


we can also conver the numpy arrays into the tensors and the  tensors into the numpy

In [71]:
import numpy as np
a=np.array([1,2,3])
print(a)
#convert into the tensors
a=torch.from_numpy(a)
print(a)


[1 2 3]
tensor([1, 2, 3])


In [72]:
a=torch.tensor([1,2,3])
print(a)
#convert to the numpy
a=a.numpy()
print(a)

tensor([1, 2, 3])
[1 2 3]
